n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
n3 = int(input('Digite mais um número: '))
n4 = int(input('Digite um último número: '))
v = (n1, n2, n3, n4)
print('Você digitou os valores {}'.format(v))
